module.exports.descriptors = [
    'Forest',
    'Brent\'s',
    'Kara\'s',
    'Corinne\'s',
    'Stephen\'s',
    'Family',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Group Camp',
    'Woods',
    'Ghost Town',
    'Camp',
    'Spring',
    'Forest',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Plantation',
    'Spring',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]
